version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379
    volumes:
      - ./data:/app/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"